### ISSUE TITLE
How to make companies sign the covenant?

### ISSUE THREAD

**Issue by ocornut** [aboodman/tythe#1]
Hello,

Just stumbled on this, good initiative! Quick thoughts.

My immediate thought is that the main difficulty to solve is:
> (2) Companies take The Tythe Covenant by posting it to social media, or on their website

Do you have a strategy or further thoughts on how to implement this? PR, lobbying? Starting small with companies we work at or know around us, before aiming at the bigger ones? Would you be able to make 5 companies that you know take a covenant like that?

My gut feeling is that I think we'd need some form of process slash enforcement for this to be viable. Who is going to run `go-tythe` otherwise, which process or metholodogy will make them do it on a regular basis? Who is the "owner" of this within the company?

Maybe some soft indirect enforcement "please try to name xxx projects you helped this year" would be helpful too.

**Comment by aboodman** [comment]
Hi @ocornut! And thanks for issue #1 ;-).

I've talked to a handful of friends who are running companies or engineering teams at various sized companies from small startups, to unicorn pre-IPO companies, to public companies. Surprisingly, most were pretty open to something like this. I received several variants of "yeah, people on my team are already asking about contributing to open source maintenance - but we don't know how to do it in a generalized, uniform way" and "we would likely do this if it appeared to be the way the world was going".

So there is going to be a bit of a chicken/egg situation, but to me it looks solvable on the company side at least. Basically, if lots of devs wanted this, and were public about it, and there was a tool that made it very easy, then lots of companies would just start doing it voluntarily. Maybe I'm naive, but that's my read.

I actually kind of think that generating a movement of devs asking for this will be more of the trick.

Would you add `tythe.json` to your libraries? Why or why not?

> Do you have a strategy or further thoughts on how to implement this? PR, lobbying? Starting small with companies we work at or know around us, before aiming at the bigger ones?

I do think that starting with small companies is going to be the way to do it. And probably initially it will take the form of going to companies, looking at their deps trees, and tracking down those devs and talking to them to get them to add the metadata.

> Would you be able to make 5 companies that you know take a covenant like that?

I feel like I would, yeah. Maybe I'm crazy :).

> Who is going to run `go-tythe` otherwise, which process or metholodogy will make them do it on a regular basis?

So this maybe isn't clear, but it feels important to me that tythe is double opt-in. Both devs and companies decide to agree to do it. So on the company side:

  1. Publicly make the covenant
  2. Run the software (paying devs as a side-effect)

I think that once a company takes step 1, taking step 2 will be almost universal. This is because the reputation cost of breaking the promise would be large, and it would be hard to keep a secret (companies are composed of lots of people, many engineers who would believe in this effort). I imagine `go-tythe` would have a dashboard intended to be visible to all engineers inside a company to enhance this effect.

I think that taking step 1 is the trickier bit, but like I said, I don't think it's actually that hard for small companies, or for bigger companies once it becomes clear this is how the world is going. Remember the tythe is only 1% of engineering costs.

> Who is the "owner" of this within the company?

Depends on the size of the company. At smallcos it will just be the CTO or VP Eng. At bigger companies there is already typically an head of open source. This person already does things like make sure open source licenses are adhered to, and it would be natural for them to inherit ownership of this too.

**Comment by aboodman** [comment]
Given your thumbs-up going to mark this resolved :).

**Comment by ocornut** [comment]
Apologies @aboodman I didn't get back to you on this.
I wasn't able to put much mind-share into this idea hence my lack of answer, but I appreciate the details on yours.

To answer that part:

> I actually kind of think that generating a movement of devs asking for this will be more of the trick.
> Would you add tythe.json to your libraries? Why or why not?

Ironically, while I would for most of my projects, for my currently successful project I would be hesitant but _only_ because I have very absurdly stringent rules about adding non-core files in the root directory of the project. I would prefer if it could fit in a standard directory (e.g. docs/) or a totally arbitrary directory (for my project I would ideally put it in misc/tythe/ along with a README). That's a small detail but giving you this feedback. Mind you my project is not representative of most open-source software (it is intentionally bending away from lots of standards).
